### ISSUE TITLE
Create script to print details of oxd_id entry

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxd#199]
Mike:
We used to be able to look at the JSON for a given oxd id. Now that it's in a database, I don't understand how I can check what is the OP host for a given oxd-id. It may not be feasible for the devops person to login to the oxd billing portal.  I think there needs to be a script in the /bin folder

-l option (i.e. list) should return all oxd_id's + name (if available) in some nice format
-d oxd_id should delete the entry
-change the name of the of the script to **lsox** and **lsox.bat**

**Comment by yuriyz** [comment]
Done in 3.1.4, now we have `oxd-show.bat` and `oxd-show.sh` scripts which prints entry from database as JSON by `oxd_id`.

```
../bin/oxd-show.sh -oxd_id d8cc6dea-4d66-4995-b6e1-da3a33722f2e

./oxd-server-distribution/bin>set LIB=../lib

./oxd-server-distribution/bin>set CONF=../conf/oxd-conf.json

./oxd-server-distribution/bin>echo CONF=../conf/oxd-conf.json
CONF=../conf/oxd-conf.json

./oxd-server-distribution/bin>start /b java -Doxd.server.config=../conf/oxd-conf.json -cp ../lib/bcprov-jdk15on-1.54.jar;../lib/oxd-server-jar-with-dependencies.jar org.xd

./oxd-server-distribution/bin>JSON for oxd_id d8cc6dea-4d66-4995-b6e1-da3a33722f2e
{"scope":["openid","uma_protection","profile"],"contacts":[],"pat":null,"rpt":null,"oxd_id":"d8cc6dea-4d66-4995-b6e1-da3a33722f2e","op_host":"https://ce-dev4.gluu.org","op_discover
```

![image](https://user-images.githubusercontent.com/2013070/41347463-69141b1a-6f12-11e8-82ec-c00617ec2be6.png)

**Comment by yuriyz** [comment]
Also if hit script without parameters it prints hints.
![image](https://user-images.githubusercontent.com/2013070/41349528-d507c910-6f18-11e8-921e-82eae6c819e7.png)

**Comment by willow9886** [comment]
@yuriyz is all this information available to ecommerce via the license server?

**Comment by yuriyz** [comment]
@willow9886 this is script which print JSON from oxd database. License Server doesn't know all those details and thus ecom. If we need to let ecom know about client details more then we can think about `get_rp` by `oxd_id` or some other solution.

**Comment by nynymike** [comment]
* `-l` option (i.e. list) should return all oxd_id's  + name (if available) in some nice format
* `-d oxd_id` should delete the entry
* change the name of the of the script to `lsox` and `lsox.bat`

**Comment by yuriyz** [comment]
Added docs how to view h2 database for 3.1.3 version [here in FAQ](https://gluu.org/docs/oxd/3.1.3/faq/#how-can-i-view-data-inside-oxd-database-manually-without-oxd-server).

Added support for `-l` and `-d` flags in 3.1.4 version.

**Comment by natt-tester** [comment]
I've followed the FAQ and managed to set up the h2 connection, but I can't see the oxd-show.bat and oxd-show.sh scripts in /oxd-server/bin:

**Comment by yuriyz** [comment]
It was renames as requested by Mike in comment to this ticket above, name is `lsox.sh` and according to your screenshot it is inside.  
About `bat`, it is in zip as suggested by docs. Because for Windows we give just zip file, no package as for Unix based OSs, see https://gluu.org/docs/oxd/3.1.4/install/#windows.

**Comment by natt-tester** [comment]
@yuriyz I think the script is flawed; I tried different commands, but it keeps giving me a NPE:

`root@osboxes:/opt/oxd-server/bin# sh 
.env            npm-debug.log   oxd-start.sh    
lsox.sh         oxd-client.log  
root@osboxes:/opt/oxd-server/bin# sh lsox.sh 
BASEDIR=.
CONF=./../conf/oxd-conf.json
Exception in thread "main" java.lang.NullPointerException
    at org.xdi.oxd.server.Cli.tryToConnectToRunningOxd(Cli.java:111)
    at org.xdi.oxd.server.Cli.main(Cli.java:82)
root@osboxes:/opt/oxd-server/bin# chmod 77 lsox.sh 
root@osboxes:/opt/oxd-server/bin# ls
lsox.sh  npm-debug.log  oxd-client.log  oxd-start.sh
root@osboxes:/opt/oxd-server/bin# ./lsox.sh 
BASEDIR=.
CONF=./../conf/oxd-conf.json
Exception in thread "main" java.lang.NullPointerException
    at org.xdi.oxd.server.Cli.tryToConnectToRunningOxd(Cli.java:111)
    at org.xdi.oxd.server.Cli.main(Cli.java:82)
root@osboxes:/opt/oxd-server/bin#`

**Comment by yuriyz** [comment]
Fixed, we had bad reference to configuration file in the script (see 7748814).

**Comment by natt-tester** [comment]
- l option (i.e. list) should return all oxd_id's + name (if available) in some nice format
root@osboxes:/opt/oxd-server/bin#   sh lsox.sh -l
BASEDIR=.
CONF=/etc/oxd/oxd-server/oxd-conf.json
7dd7951c-f495-4c03-9b79-8f206863b9a0
878e4648-4bc5-4eb2-80bf-3ffa09b16e51
8b265394-24d1-48fc-81c2-be01a2a906a0
35ecda62-53d8-4dad-8eba-a6ba7a645229
f5641357-c0a9-49ad-b933-912b94f49272
728c103c-a092-4c2d-bd2f-6068cbf068ce
27c21168-2f2e-4dbb-a1c0-704941071017
edbee55f-80fc-48d8-a894-c7436d77e7ff
6811a0d1-773c-4c9e-8976-b0f7a44c40df
1b8fb665-d2a8-4cb5-87c4-835ecb916e38
ddcff715-8769-4613-919c-ab44baec4882

- d oxd_id should delete the entry
root@osboxes:/opt/oxd-server/bin#   sh lsox.sh -d b546c413-93c5-42f9-b2fc-67510211836b
BASEDIR=.
CONF=/etc/oxd/oxd-server/oxd-conf.json
Entry removed successfully.

- change the name of the of the script to lsox and lsox.bat

**Comment by yuriyz** [comment]
I'm not sure we need any names while listed existing oxd_ids in the database. The parameter of command says `-l,--list                list all oxd_ids inside oxd database`.
So it just lists all oxd_ids. Anyway, if we can improve it I'm open to ideas. Please open separate ticket for improvement and schedule for 4.0 milestone. It is not critical.

**Comment by yuriyz** [comment]
Done. Example output
```
oxd_id                                client_name
5e0a4978-18ff-4776-924d-5303a8466241  null
da086f2b-ae17-47d9-aeb5-c8f7a7e2c334  null
4e670c2c-37fc-4c5f-aa7f-1dbaaaf6ea1e  null
f540da31-7c70-4b8f-9084-40535d721ae9  null
196ea518-f5e1-4f50-ab43-33857946209d  null
79a046dc-8b3e-4e69-bc4a-a133f51e26ae  null
2dc2072b-acae-45d3-aa7e-a8a9767a0a9f  null
c691d5a6-5af7-44bf-a545-dea2a9987739  null
2922e3d9-9b3b-4a82-b466-d12d30d23017  null
ba13837f-e296-4d69-858c-5f919c97c434  null
```

**Comment by yuriyz** [comment]
fixed in 3.1.4

**Comment by natt-tester** [comment]
Checked in the new 3.1.4: it's DONE.
<img width="666" alt="ubuntu14_final" src="https://user-images.githubusercontent.com/38302725/47344181-9a5d4180-d6f3-11e8-8745-9cb6fa10c70b.png">

**Comment by natt-tester** [comment]
@yuriyz, I've just found an uncaught NPE in the script. It seems to occur when you either malform the `-d` command, want to delete an already removed client or remove a non-existent one. Also for `sh lsox.sh -oxd_id` when you malform it, use an already removed client or a non-existent one. `-l` seems to be working fine.

`root@osboxes:/opt/oxd-server/bin# sh lsox.sh -l
BASEDIR=.
CONF=/etc/oxd/oxd-server/oxd-conf.json
oxd_id                                client_name
6398c7f0-3834-465c-9dd3-b2b17adc6758  null
9597d935-55c7-45ac-9430-b7b2b58599ba  newtest2
aa5a9833-243f-4dbf-b0f4-263787664baf  null
fd9db552-bf5e-47d2-82b0-ba71c9d78155  newtest1
root@osboxes:/opt/oxd-server/bin# sh lsox.sh -d ba71c9d78155
BASEDIR=.
CONF=/etc/oxd/oxd-server/oxd-conf.json
Exception in thread "main" java.lang.NullPointerException
    at org.xdi.oxd.server.Cli.tryToConnectToRunningOxd(Cli.java:164)
    at org.xdi.oxd.server.Cli.main(Cli.java:91)
root@osboxes:/opt/oxd-server/bin# sh lsox.sh -dd ba71c9d78155
BASEDIR=.
CONF=/etc/oxd/oxd-server/oxd-conf.json
Exception in thread "main" java.lang.NullPointerException
    at org.xdi.oxd.server.Cli.tryToConnectToRunningOxd(Cli.java:164)
    at org.xdi.oxd.server.Cli.main(Cli.java:91)
root@osboxes:/opt/oxd-server/bin# sh lsox.sh -dd
BASEDIR=.
CONF=/etc/oxd/oxd-server/oxd-conf.json
Exception in thread "main" java.lang.NullPointerException
    at org.xdi.oxd.server.Cli.tryToConnectToRunningOxd(Cli.java:164)
    at org.xdi.oxd.server.Cli.main(Cli.java:91)
root@osboxes:/opt/oxd-server/bin# `

[errors_oxd-server.log](https://github.com/GluuFederation/oxd/files/2508666/errors_oxd-server.log)

**Comment by yuriyz** [comment]
Thanks, fixed error messages if parameters are malformed.

**Comment by natt-tester** [comment]
@yuriyz, the messages are fine and there are no NPEs, but the log still shows errors:
```
2018-10-24 07:42:52,366 ERROR [org.xdi.oxd.server.persistence.SqlPersistenceServiceImpl] Failed to find RP by id: lvw. Error: No data is available [2000-194]
org.h2.jdbc.JdbcSQLException: No data is available [2000-194]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
    at org.h2.message.DbException.get(DbException.java:179)
    at org.h2.message.DbException.get(DbException.java:155)
    at org.h2.message.DbException.get(DbException.java:144)
    at org.h2.jdbc.JdbcResultSet.checkOnValidRow(JdbcResultSet.java:3212)
    at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3218)
    at org.h2.jdbc.JdbcResultSet.get(JdbcResultSet.java:3235)
    at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:308)
    at org.xdi.oxd.server.persistence.SqlPersistenceServiceImpl.getRp(SqlPersistenceServiceImpl.java:117)
    at org.xdi.oxd.server.persistence.PersistenceServiceImpl.getRp(PersistenceServiceImpl.java:49)
    at org.xdi.oxd.server.service.RpService.getRp(RpService.java:58)
    at org.xdi.oxd.server.op.BaseOperation.getRp(BaseOperation.java:116)
    at org.xdi.oxd.server.op.RemoveSiteOperation.execute(RemoveSiteOperation.java:29)
    at org.xdi.oxd.server.op.RemoveSiteOperation.execute(RemoveSiteOperation.java:13)
    at org.xdi.oxd.server.Processor.process(Processor.java:74)
    at org.xdi.oxd.server.Processor.process(Processor.java:49)
    at org.xdi.oxd.server.SocketProcessor.run(SocketProcessor.java:55)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
2018-10-24 07:42:52,373 ERROR [org.xdi.oxd.server.Processor] 
ErrorResponseException{errorResponseCode=ErrorResponseCode{value='invalid_oxd_id', description='Invalid oxd_id. Unable to find site for oxd_id. It does not exist or removed from the server. Please use register_site command to register a site.'}}
    at org.xdi.oxd.server.service.ValidationService.validate(ValidationService.java:178)
    at org.xdi.oxd.server.service.RpService.getRp(RpService.java:63)
    at org.xdi.oxd.server.op.BaseOperation.getRp(BaseOperation.java:116)
    at org.xdi.oxd.server.op.RemoveSiteOperation.execute(RemoveSiteOperation.java:29)
    at org.xdi.oxd.server.op.RemoveSiteOperation.execute(RemoveSiteOperation.java:13)
    at org.xdi.oxd.server.Processor.process(Processor.java:74)
    at org.xdi.oxd.server.Processor.process(Processor.java:49)
    at org.xdi.oxd.server.SocketProcessor.run(SocketProcessor.java:55)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
2018-10-24 07:42:52,374 TRACE [org.xdi.oxd.server.Processor] Send back response: {"status":"error","data"
``` 
What can we do with it?

**Comment by yuriyz** [comment]
Those are validation exceptions. We should not do anything with it.
